### ISSUE TITLE
test_flight2 stops logging after a few data points

### ISSUE THREAD

**Issue by Shaun1** [PumpkinSpace/BBBTelemetry#23]
also outputs text to bash shell - didn't do that before and probably shouldn't now.

**Comment by asmalldev** [comment]
I've been running tests as: `nohup testflight.py &` which seems to work okay. But after some googling, it looks like the best way to do it requires two commands:
 
`python test_flight.py &`
`disown <pid>`

and you can get the pid with `echo $!` after executing test script if the shell doesn't print it already
